version: "3"

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"

  db-test:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"

  test:
    build: .
    volumes:
      - .:/phoenix
    command: >
       bash -c "./scripts/wait-for-it.sh db-test:5432  && alembic upgrade head && pytest -v;sleep infinity"
    links:
      - db-test:db
    depends_on:
      - db-test

  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn phoenix.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/phoenix
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  postgres_data:
