version: "3"

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"

  db-test:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"

  test:
    build:
      context: .
      dockerfile: phoenix-api/Dockerfile
    volumes:
      - ./phoenix-api:/usr/src/app/phoenix-api
    command: >
       bash -c "/usr/src/app/phoenix-api/scripts/wait-for-it.sh db-test:5432  && alembic upgrade head && pytest -v;sleep infinity"
    links:
      - db-test:db
    depends_on:
      - db-test
    working_dir: /usr/src/app/phoenix-api

  phoenix-api:
    build:
      context: .
      dockerfile: phoenix-api/Dockerfile
    command: bash -c "alembic upgrade head && uvicorn phoenix.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./phoenix-api:/usr/src/app/phoenix-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /usr/src/app/phoenix-api


  phoenix-ui:
    build:
      context: .
      dockerfile: phoenix-ui/Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./phoenix-ui/dist/phoenix-ui:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/sites-available/default
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - phoenix-api

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8100:80"
      - "8443:443"
    depends_on:
      - phoenix-api

volumes:
  postgres_data:
