"""added image field

Revision ID: 1a33b4fd4c95
Revises: 907ae18ae99f
Create Date: 2024-02-23 12:45:29.222811

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1a33b4fd4c95'
down_revision: Union[str, None] = '85d42e527105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments_rent', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('apartments_sale', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments_sale', 'image')
    op.drop_column('apartments_rent', 'image')
    # ### end Alembic commands ###
